//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theraphy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string CONTACT { get; set; }
        public string TIMING { get; set; }
        public string CLINIC_ADDRESS { get; set; }
        public string CLINIC_EMAIL { get; set; }
        public string CLINIC_CONTACT { get; set; }
        public string LOGO_NAME { get; set; }
        public string LOGO_IMAGE { get; set; }
        public string FACEBOOK { get; set; }
        public string TWITTER { get; set; }
        public string GOOGLE_PLUS { get; set; }
        public string LINKED_IN { get; set; }
        public string YOUTUBE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    
        public virtual login login { get; set; }
        public virtual login login1 { get; set; }
    }
}
